[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "curie-cli"
version = "0.1.0"
description = "CLI for the Curie scientific AI platform"
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.11"
dependencies = [
    "typer>=0.12.0",
    "httpx>=0.27.0",
    "rich>=13.0.0",
    "pyfiglet>=1.0.4"
]

[project.urls]
Repository = "https://github.com/curieapi/curie-cli"
Homepage = "https://curie.sh"

[project.scripts]
curie = "curie.cli:app"

[project.optional-dependencies]
dev = ["pytest", "pytest-asyncio"]

[tool.hatch.build.targets.wheel]
packages = ["curie"]